language: php

php:
  - 7.4

env:
  - PHP_BIN=php

before_install:
  - composer self-update

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/tester -p $PHP_BIN ./tests/ -s

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done