language: php

php:
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/tester -s ./tests

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done